trigger:
- main

pool:
  name: Default
  
steps:
- task: synopsys-coverity@1
  inputs:
    coverityService: 'coverity-connect'
    projectName: 'test'
    streamName: 'test'
    coverityBuildDirectory: '$(Build.Repository.LocalPath)'
    buildCommand: '"C:\Program Files\Apache Maven\bin\mvn" -B compile'
    allowUntrusted: true

- script: |
    echo "Listing potential Coverity result locations..."
    dir "$(Build.Repository.LocalPath)" /S /A
  displayName: 'List Directories and Files'

- script: |
    echo "Checking for common Coverity result directories..."
    if exist "$(Build.Repository.LocalPath)\cov-int" (
      dir "$(Build.Repository.LocalPath)\cov-int" /S /A
    ) else (
      echo "cov-int directory not found"
    )
  displayName: 'Check Common Coverity Output Directory'

- task: CodeDxUploadFilse@0
  inputs:
    codeDxUrl: 'http://localhost/srm/projects/'
    projectId: 'test2'
    apiKey: 'bNostnbTYFKNMqMoHq3Vme137yp5VcRU8zGIfgcl'
    filePaths: coverity-results.sarif
