trigger:
- main

pool:
  name: Default
  
steps:
- task: synopsys-coverity@1
  inputs:
    coverityService: 'coverity-connect'
    projectName: 'test'
    streamName: 'test'
    coverityBuildDirectory: '$(Build.Repository.LocalPath)'
    buildCommand: '"C:\Program Files\Apache Maven\bin\mvn" -B compile'
    allowUntrusted: true

- script: |
    # Convert Coverity analysis results to SARIF format
    cov-format-errors --dir $(Build.Repository.LocalPath)/cov-int --sarif-output coverity-results.sarif
  displayName: 'Convert Coverity Results to SARIF'

- task: CodeDxUploadFilse@0
  inputs:
    codeDxUrl: 'http://localhost/srm/projects/'
    projectId: 'test2'
    apiKey: 'bNostnbTYFKNMqMoHq3Vme137yp5VcRU8zGIfgcl'
    filePaths: coverity-results.sarif
