trigger:
- main

pool:
  name: vm
  
steps:
- task: synopsys-coverity@1
  inputs:
    coverityService: 'coverity-connect'
    projectName: 'test'
    streamName: 'test'
    coverityBuildDirectory: '$(Build.Repository.LocalPath)'
    buildCommand: '/home/***/cov-analysis-linux64-2024.6.0/bin/cov-build --dir $(Build.Repository.LocalPath)/idir mvn clean install'
    allowUntrusted: true

