trigger:
- main

pool:
  name: Default

steps:
- task: synopsys-coverity@1
  inputs:
    coverityService: 'coverity-connect'
    projectName: 'test'
    streamName: 'test'
    coverityBuildDirectory: '$(Build.Repository.LocalPath)'
    coverityAnalysisType: 'incremental'
    allowUntrusted: true
    covAnalyzeArgs: '--webapp-security'
    covDesktopArgs: '--analyze-captured-source'