trigger:
  - main

pool:
  name: Default

steps:
  # Step 1: Run the initial full build and analysis (only run manually the first time)
  - task: synopsys-coverity@1
    displayName: 'Run Coverity Full Scan (Initial Setup)'
    inputs:
      coverityService: 'coverity-connect'
      projectName: 'test'
      streamName: 'test'
      coverityBuildDirectory: '$(Build.Repository.LocalPath)'
      coverityAnalysisType: 'full'
      buildCommand: 'mvn clean install'
      allowUntrusted: true
      covAnalyzeArgs: '--webapp-security'
    condition: eq(variables['Build.Reason'], 'Manual')  # Run only when manually triggered

  # Step 2: Publish the `idir` as a pipeline artifact
  - task: PublishPipelineArtifact@1
    displayName: 'Publish idir as Artifact'
    inputs:
      targetPath: '$(Build.Repository.LocalPath)/idir'
      artifact: 'idir'
      publishLocation: 'pipeline'
    condition: eq(variables['Build.Reason'], 'Manual')  # Publish only after manual full scans

  # Step 3: Download the `idir` artifact in subsequent runs
  - task: DownloadPipelineArtifact@2
    displayName: 'Download idir Artifact'
    inputs:
      artifact: 'idir'
      targetPath: '$(Build.Repository.LocalPath)/idir'
      buildType: 'current'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'Manual'))  # Skip if manual trigger

  # Step 4: Check if `idir` exists and set a variable for conditional execution
  - script: |
      if [ -d "$(Build.Repository.LocalPath)/idir" ]; then
        echo "##vso[task.setvariable variable=IdirExists]true"
      else
        echo "##vso[task.setvariable variable=IdirExists]false"
      fi
    displayName: 'Check if idir Exists'

  # Step 5: Run Incremental Analysis (only if `idir` exists)
  - task: synopsys-coverity@1
    displayName: 'Run Incremental Coverity Analysis'
    inputs:
      coverityService: 'coverity-connect'
      projectName: 'test'
      streamName: 'test'
      coverityBuildDirectory: '$(Build.Repository.LocalPath)'
      coverityAnalysisType: 'incremental'
      allowUntrusted: true
      covDesktopArgs: '--analyze-captured-source'
    condition: eq(variables['IdirExists'], 'true')  # Run only if `idir` exists
