trigger:
  - main

pool:
  name: Default

steps:
- task: synopsys-coverity@1
  inputs:
    coverityService: 'coverity-connect'
    projectName: 'test'
    streamName: 'test'
    coverityBuildDirectory: '$(Build.Repository.LocalPath)'
    coverityRunType: 'custom'
    customCoverityCommands: 'cov-run-desktop --dir /home/***/agent/_work/3/s/idir --url http://192.168.164.129:8081/ --stream test --analyze-captured-source'