trigger:
  - main

pool:
  name: Default

steps:
- task: synopsys-coverity@1
  inputs:
    coverityService: 'coverity-connect'
    projectName: 'test'
    streamName: 'test'
    coverityBuildDirectory: '$(Build.Repository.LocalPath)'
    coverityAnalysisType: 'incremental'
    customCommandArgs: true
    covDesktopArgs: '--analyze-captured-source'