trigger:
- main

pool:
  name: vm
  
steps:
- task: synopsys-coverity@1
  inputs:
    coverityService: 'coverity-connect'
    projectName: 'test'
    streamName: 'test'
    coverityBuildDirectory: '$(Build.Repository.LocalPath)'
    buildCommand: '"C:\Program Files\Apache Maven\bin\mvn" -B compile'
    allowUntrusted: true

