trigger:
- main

pool:
  name: Default

steps:
- task: synopsys-coverity@1
  inputs:
    coverityService: 'coverity-connect'
    projectName: 'test'
    streamName: 'test'
    coverityBuildDirectory: '$(Build.Repository.LocalPath)'
    coverityAnalysisType: 'incremental'
    allowUntrusted: true
    covDesktopArgs: '--analyze-captured-source'

  env:
    COVERITY_TOOL_HOME: $(COVERITY_TOOL_HOME)
    COV_USER: admin
    COV_URL: 'http://192.168.164.129:8081'